services:
  mysql:
    image: mysql:latest
    container_name: inventory-service-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - "3316:3306"
    volumes:
      - ./mysql:/var/lib/mysql
